package com.oceaneconsulting.seleniumhtmlunit;

import org.junit.*;
import org.junit.runner.RunWith;
import org.junit.runners.BlockJUnit4ClassRunner;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static junit.framework.Assert.*;

/**
 * Created by ubuntu on 3/27/14.
 */
@RunWith(BlockJUnit4ClassRunner.class)
@FixMethodOrder(MethodSorters.DEFAULT)
public class HelloWorldTest {

    private static final Logger logger = LoggerFactory.getLogger(HelloWorldTest.class);

    private WebDriver htmlUnitDriver;
    private WebDriver firefoxDriver;

    @Before
    public void setUp() {
        htmlUnitDriver = new HtmlUnitDriver();
        firefoxDriver = new FirefoxDriver();
    }


    @Test
    public void createWebDriver() {

        final long beginHtmlUnit = System.currentTimeMillis();
        htmlUnitDriver.get("http://www.oceaneconsulting.com");

        logger.info("HtmlUnit execution took {}", (System.currentTimeMillis() - beginHtmlUnit));

        logger.info("**************************************");

        final long beginFirefox = System.currentTimeMillis();
        firefoxDriver.get("http://www.oceaneconsulting.com");

        logger.info("Firefox execution took {}", (System.currentTimeMillis() - beginFirefox));



    }

    private void comparePageSources() {
        logger.info("pages generated By Both drivers are equals? response: {}",
                htmlUnitDriver.getPageSource().compareToIgnoreCase(firefoxDriver.getPageSource()));
        assertEquals(htmlUnitDriver.getPageSource(), firefoxDriver.getPageSource());
    }

    @After
    public void tearDown() {
        htmlUnitDriver.quit();
        firefoxDriver.quit();

    }
}
